config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/eosc-search-service:
      branch: development
      repo: https://github.com/cyfronet-fid/eosc-search-service.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-gold-albatross.sh
        container: qc.acc_smelly-goldenrod-russel
  QC.Doc:
    repos:
      github.com/cyfronet-fid/eosc-search-service find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-puce-bracke.sh
        container: qc.doc_nerdy-turquoise-ostrich
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-scarlet-chameleon.sh
        container: qc.doc_sunny-orange-cattle
      github.com/cyfronet-fid/eosc-search-service markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amethyst-chipmunk.sh
        container: qc.doc_snippy-chocolate-hyrax
  QC.Lic:
    repos:
      github.com/cyfronet-fid/eosc-search-service licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-chestnut-bear.sh
        container: qc.lic_nippy-lime-cheetah
  QC.Sec:
    repos:
      github.com/cyfronet-fid/eosc-search-service bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-pumpkin-barnacle.sh
        container: qc.sec_jumpy-mauve-fousek
  QC.Sty:
    repos:
      github.com/cyfronet-fid/eosc-search-service flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-ecru-gibbon.sh
        container: qc.sty_wiggy-cyan-rhinoceros
      github.com/cyfronet-fid/eosc-search-service hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-orange-swan.sh
        container: qc.sty_squeaky-red-quail
      github.com/cyfronet-fid/eosc-search-service jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-apricot-angelfish.sh
        container: qc.sty_smelly-flax-bulldog
  QC.Uni:
    repos:
      github.com/cyfronet-fid/eosc-search-service pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-puce-newt.sh
        container: qc.uni_sleepy-chocolate-civet
  QC.Ver:
    repos:
      github.com/cyfronet-fid/eosc-search-service get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-puce-fish.sh
        container: qc.ver_homely-amaranth-anteater
timeout: 5400
