config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/eosc-search-service:
      branch: development
      repo: https://github.com/cyfronet-fid/eosc-search-service.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-heliotrope-raccoon.sh
        container: qc.acc_scummy-lilac-spitz
  QC.Doc:
    repos:
      github.com/cyfronet-fid/eosc-search-service find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cardinal-tarsier.sh
        container: qc.doc_stuffy-teal-fousek
      github.com/cyfronet-fid/eosc-search-service git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-aquamarine-javanese.sh
        container: qc.doc_nerdy-asparagus-crane
      github.com/cyfronet-fid/eosc-search-service markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-coral-grouse.sh
        container: qc.doc_muggy-black-beaver
  QC.Lic:
    repos:
      github.com/cyfronet-fid/eosc-search-service licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-dandelion-uguisu.sh
        container: qc.lic_sloppy-cinnamon-frigatebird
  QC.Sec:
    repos:
      github.com/cyfronet-fid/eosc-search-service bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-vermilion-nightingale.sh
        container: qc.sec_thirsty-violet-walrus
  QC.Sty:
    repos:
      github.com/cyfronet-fid/eosc-search-service flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-black-bulldog.sh
        container: qc.sty_gimpy-sangria-clam
      github.com/cyfronet-fid/eosc-search-service hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-charcoal-warthog.sh
        container: qc.sty_droopy-amethyst-caracal
      github.com/cyfronet-fid/eosc-search-service jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-copper-crane.sh
        container: qc.sty_shabby-olive-squid
  QC.Uni:
    repos:
      github.com/cyfronet-fid/eosc-search-service pytest:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ivory-okapi.sh
        container: qc.uni_craggy-tomato-avocet
  QC.Ver:
    repos:
      github.com/cyfronet-fid/eosc-search-service get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-chestnut-crab.sh
        container: qc.ver_flaky-buff-hamster
timeout: 5400
